### ISSUE TITLE
include missing dependencies

### ISSUE THREAD

**Issue by sugatoray** [conda-forge/pytorch_geometric-feedstock#22]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It seems that the following two dependencies are missing form the recipe.

- `pyyaml`
- `yacs`

See the details [here](https://github.com/conda-forge/staged-recipes/pull/18663): [(error)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=493942&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=1579)

```sh
torch-geometric 2.0.3 requires pyyaml, which is not installed.
torch-geometric 2.0.3 requires yacs, which is not installed.
```

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by hadim** [comment]
It should be fine now with the latest release. Please reopen if needed.
